# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-21 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.BooleanField(default=False)),
                ('school', models.CharField(max_length=64)),
                ('hight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'tb_stu',
            },
        ),
    ]
